/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#bec6e0",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-tertiary-fixed-variant": "#3f465c",
        "tertiary-container": "#6c748b",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary-fixed": "#3e0022",
        "surface-container-high": "#e6e8ea",
        surface: "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb0cd",
        "on-secondary-container": "#600037",
        "tertiary-fixed": "#dae2fd",
        "surface-tint": "#494bd6",
        "primary-container": "#6063ee",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        primary: "#4648d4",
        "secondary-container": "#fd56a7",
        "inverse-on-surface": "#eff1f3",
        background: "#f7f9fb",
        "outline-variant": "#c7c4d7",
        tertiary: "#545c72",
        secondary: "#b4136d",
        "inverse-primary": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "on-surface-variant": "#464554",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#fffbff",
        "on-background": "#191c1e",
        "on-tertiary-container": "#fefcff",
        "secondary-fixed": "#ffd9e4",
        "surface-container-low": "#f2f4f6",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#8c0053",
        "on-tertiary-fixed": "#131b2e",
        outline: "#767586",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
